spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog_system?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 57502
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 新增 Druid 配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000